global:
  scrape_interval: 10s

scrape_configs:
- job_name: vmagent
  static_configs:
  - targets:
    - vmagent:8429

- job_name: cadvisor
  static_configs:
  - targets:
    - cadvisor:8080

- job_name: docker-state-exporter
  static_configs:
  - targets:
    - docker-state-exporter:8080

- job_name: node-exporter
  static_configs:
  - targets:
    - node-exporter:9100
